In [1]:
#import libraries

import pandas as pd
import numpy as np
import os

In [2]:
path = r'/Users/shirwetelfeel/Desktop/Data analysis /tasks/Data immersion/Achievment 4/14-02-2022 Instacart Basket Analysis'

In [4]:
ords_prods_merge =  pd.read_pickle(os.path.join(path, '/Users/shirwetelfeel/Desktop/Data analysis /tasks/Data immersion/Achievment 4/14-02-2022 Instacart Basket Analysis/Data/Prepared Data/orders_products_merged.pkl'))

In [5]:
# create a subset called df for the first 1000000 cells
df = ords_prods_merge[:1000000]

In [6]:
df.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range,Busiest days,busiest_period_of_day
0,2539329,1,prior,1,2,8.0,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly days,Average orders
1,2398795,1,prior,2,3,7.0,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Average orders
2,473747,1,prior,3,3,12.0,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders
3,2254736,1,prior,4,4,7.0,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Average orders
4,431534,1,prior,5,4,15.0,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders

In [8]:
df.shape

(999060, 18)

In [9]:
#creating a new column by grouping 
df.groupby('product_name')

In [10]:
##aggregate the department _id by average order number
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                14.793523
2                17.091743
3                17.920595
4                17.893164
5                15.214270
6                15.382228
7                17.699986
8                16.485269
9                15.965921
10               20.091818
11               16.485395
12               15.617735
13               16.485052
14               17.523474
15               15.690354
16               18.014342
17               16.155822
18               19.606536
19               17.630640
20               17.138204
21               21.996844

In [11]:
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [12]:
ords_prods_merge.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range,Busiest days,busiest_period_of_day,max_order
0,2539329,1,prior,1,2,8.0,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly days,Average orders,10
1,2398795,1,prior,2,3,7.0,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Average orders,10
2,473747,1,prior,3,3,12.0,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders,10
3,2254736,1,prior,4,4,7.0,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Average orders,10
4,431534,1,prior,5,4,15.0,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders,10

In [13]:
#showing the 100 rows
ords_prods_merge.head(100)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range,Busiest days,busiest_period_of_day,max_order
0,2539329,1,prior,1,2,8.0,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly days,Average orders,10
1,2398795,1,prior,2,3,7.0,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Average orders,10
2,473747,1,prior,3,3,12.0,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders,10
3,2254736,1,prior,4,4,7.0,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Average orders,10
4,431534,1,prior,5,4,15.0,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,3226575,360,prior,1,5,12.0,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,3
96,1469869,377,prior,3,5,17.0,3.0,196,9,0,Soda,77,7,9.0,both,Mid-range product,Regularly days,Average orders,3
97,1927023,387,prior,2,4,10.0,22.0,196,3,0,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders,8
98,858092,420,prior,4,1,19.0,30.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Busiest days,Average orders,22
99,119314,420,prior,5,3,19.0,16.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Average orders,22

In [14]:
##pandas not to assign any options regarding the maximum number of rows to display.
pd.options.display.max_rows = None

In [15]:
ords_prods_merge.head(100)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range,Busiest days,busiest_period_of_day,max_order
0,2539329,1,prior,1,2,8.0,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly days,Average orders,10
1,2398795,1,prior,2,3,7.0,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Average orders,10
2,473747,1,prior,3,3,12.0,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders,10
3,2254736,1,prior,4,4,7.0,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Average orders,10
4,431534,1,prior,5,4,15.0,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders,10
5,3367565,1,prior,6,2,7.0,19.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Average orders,10
6,550135,1,prior,7,1,9.0,20.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Average orders,10
7,3108588,1,prior,8,1,14.0,14.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most orders,10
8,2295261,1,prior,9,1,16.0,0.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Average orders,10
9,2550362,1,prior,10,4,8.0,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Average orders,10
10,2968173,15,prior,15,1,9.0,7.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Busiest days,Average orders,22
11,1870022,15,prior,17,2,16.0,8.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Average orders,22
12,1911383,15,prior,18,2,11.0,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,22
13,2715276,15,prior,21,1,9.0,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Average orders,22
14,487368,15,prior,22,1,10.0,14.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most orders,22
15,2293453,19,prior,2,5,14.0,6.0,196,3,0,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,9
16,1973799,19,prior,5,6,12.0,8.0,196,15,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,9
17,532817,19,prior,7,4,17.0,6.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Average orders,9
18,1573906,21,prior,10,3,10.0,6.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders,33
19,1593000,31,prior,10,3,8.0,7.0,196,17,0,Soda,77,7,9.0,both,Mid-range product,Slowest days,Average orders,20
20,2231262,31,prior,17,3,11.0,8.0,196,14,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders,20
21,2580647,43,prior,6,4,16.0,4.0,196,9,0,Soda,77,7,9.0,both,Mid-range product,Slowest days,Average orders,11
22,2187180,43,prior,9,4,12.0,3.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders,11
23,2497897,52,prior,1,1,9.0,NaN,196,4,0,Soda,77,7,9.0,both,Mid-range product,Busiest days,Average orders,27
24,1318871,52,prior,2,1,10.0,7.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most orders,27
25,1261384,52,prior,3,1,10.0,7.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most orders,27
26,580568,52,prior,5,2,10.0,8.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,27
27,2428073,52,prior,7,2,7.0,8.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Average orders,27
28,342306,52,prior,9,1,11.0,7.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most orders,27
29,1520353,52,prior,10,2,10.0,8.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,27
30,2542086,52,prior,11,2,9.0,7.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Average orders,27
31,944694,52,prior,12,1,16.0,6.0,196,7,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Average orders,27
32,1268191,52,prior,15,2,11.0,8.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,27
33,1122089,52,prior,17,2,10.0,6.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,27
34,1498922,52,prior,18,2,10.0,14.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,27
35,180919,52,prior,19,3,8.0,8.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Average orders,27
36,2695875,52,prior,21,5,10.0,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,27
37,3205960,67,prior,1,3,11.0,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders,24
38,970922,67,prior,2,1,15.0,5.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most orders,24
39,596585,67,prior,3,1,13.0,7.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most orders,24
40,2037087,67,prior,4,2,9.0,8.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Average orders,24
41,2474111,67,prior,5,3,14.0,8.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders,24
42,1568481,67,prior,6,3,12.0,7.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders,24
43,2048527,67,prior,8,2,11.0,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,24
44,2389031,67,prior,9,2,14.0,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,24
45,2378562,67,prior,10,1,10.0,6.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most orders,24
46,1515698,67,prior,11,1,11.0,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most orders,24
47,1928050,67,prior,12,2,12.0,8.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,24
48,1949274,67,prior,13,1,10.0,6.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most orders,24
49,551869,67,prior,14,1,9.0,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Average orders,24
50,768572,67,prior,16,4,10.0,9.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders,24
51,150528,67,prior,18,5,16.0,4.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Average orders,24
52,29758,67,prior,19,0,14.0,9.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most orders,24
53,1558976,67,prior,21,1,9.0,5.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Average orders,24
54,863974,67,prior,22,1,11.0,14.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most orders,24
55,2308399,67,prior,23,1,14.0,14.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most orders,24
56,2759128,81,prior,3,1,9.0,14.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Busiest days,Average orders,7
57,1812985,81,prior,5,2,20.0,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Average orders,7
58,1889835,82,prior,1,3,15.0,NaN,196,6,0,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders,19
59,499460,82,prior,3,5,10.0,5.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,19
60,2728456,82,prior,4,0,11.0,16.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most orders,19
61,2653743,82,prior,6,4,9.0,13.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Average orders,19
62,1358880,82,prior,9,1,10.0,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most orders,19
63,343588,82,prior,10,2,11.0,1.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,19
64,3034663,82,prior,15,2,11.0,12.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,19
65,147262,82,prior,18,1,13.0,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most orders,19
66,3144004,82,prior,19,2,15.0,8.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,19
67,2126069,98,prior,3,0,9.0,25.0,196,7,0,Soda,77,7,9.0,both,Mid-range product,Busiest days,Average orders,14
68,2210120,98,prior,7,5,14.0,5.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,14
69,681011,98,prior,9,3,9.0,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Average orders,14
70,2846344,98,prior,11,4,13.0,15.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders,14
71,747431,98,prior,12,6,13.0,30.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,14
72,2383054,98,prior,13,4,11.0,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders,14
73,1993729,98,prior,14,5,8.0,8.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Average orders,14
74,1403849,109,prior,3,3,17.0,9.0,196,5,0,Soda,77,7,9.0,both,Mid-range product,Slowest days,Average orders,6
75,520620,120,prior,1,3,11.0,NaN,196,2,0,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders,3
76,3273029,120,prior,3,2,8.0,19.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Average orders,3
77,1861943,185,prior,2,1,12.0,25.0,196,10,0,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most orders,6
78,2040988,195,prior,1,1,14.0,NaN,196,2,0,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most orders,58
79,1680569,195,prior,8,1,9.0,4.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Average orders,58
80,276171,195,prior,19,5,11.0,3.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,58
81,2744976,195,prior,22,5,10.0,7.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,58
82,2781919,195,prior,25,1,14.0,4.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most orders,58
83,1738718,195,prior,31,2,8.0,4.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Average orders,58
84,3058369,195,prior,34,3,10.0,6.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders,58
85,1485596,195,prior,37,2,15.0,0.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,58
86,417035,195,prior,40,3,16.0,2.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Average orders,58
87,1615297,195,prior,47,5,10.0,2.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,58
88,1765587,195,prior,52,3,12.0,2.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders,58
89,745908,195,prior,57,4,11.0,3.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders,58
90,2505656,222,prior,17,2,12.0,1.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,70
91,3268370,222,prior,38,5,15.0,1.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,70
92,2016711,290,prior,9,5,19.0,6.0,196,8,0,Soda,77,7,9.0,both,Mid-range product,Regularly days,Average orders,51
93,2706088,290,prior,28,6,10.0,7.0,196,16,1,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,51
94,1952286,331,prior,6,5,16.0,30.0,196,8,0,Soda,77,7,9.0,both,Mid-range product,Regularly days,Average orders,8
95,3226575,360,prior,1,5,12.0,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly days,Most orders,3
96,1469869,377,prior,3,5,17.0,3.0,196,9,0,Soda,77,7,9.0,both,Mid-range product,Regularly days,Average orders,3
97,1927023,387,prior,2,4,10.0,22.0,196,3,0,Soda,77,7,9.0,both,Mid-range product,Slowest days,Most orders,8
98,858092,420,prior,4,1,19.0,30.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Busiest days,Average orders,22
99,119314,420,prior,5,3,19.0,16.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Slowest days,Average orders,22

In [16]:
##creating loyality if statement  based on max_order
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [18]:
##After executing the code to set the flags, print the frequency of your new “loyalty_flag” column using the value_counts() function:
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    481853
Loyal customer      321881
New customer        195326
Name: loyalty_flag, dtype: int64

In [19]:
#to check the execution of the loyalty_flag
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             2
2         1      New customer             3
3         1      New customer             4
4         1      New customer             5
5         1      New customer             6
6         1      New customer             7
7         1      New customer             8
8         1      New customer             9
9         1      New customer            10
10       15  Regular customer            15
11       15  Regular customer            17
12       15  Regular customer            18
13       15  Regular customer            21
14       15  Regular customer            22
15       19      New customer             2
16       19      New customer             5
17       19      New customer             7
18       21  Regular customer            10
19       31  Regular customer            10
20       31  Regular customer            17
21       43  Regular customer             6
22       43  Regular customer             9
23       52  Regular customer             1
24       52  Regular customer             2
25       52  Regular customer             3
26       52  Regular customer             5
27       52  Regular customer             7
28       52  Regular customer             9
29       52  Regular customer            10
30       52  Regular customer            11
31       52  Regular customer            12
32       52  Regular customer            15
33       52  Regular customer            17
34       52  Regular customer            18
35       52  Regular customer            19
36       52  Regular customer            21
37       67  Regular customer             1
38       67  Regular customer             2
39       67  Regular customer             3
40       67  Regular customer             4
41       67  Regular customer             5
42       67  Regular customer             6
43       67  Regular customer             8
44       67  Regular customer             9
45       67  Regular customer            10
46       67  Regular customer            11
47       67  Regular customer            12
48       67  Regular customer            13
49       67  Regular customer            14
50       67  Regular customer            16
51       67  Regular customer            18
52       67  Regular customer            19
53       67  Regular customer            21
54       67  Regular customer            22
55       67  Regular customer            23
56       81      New customer             3
57       81      New customer             5
58       82  Regular customer             1
59       82  Regular customer             3

In [20]:
ords_prods_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 999060 entries, 0 to 999059
Data columns (total 20 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   order_id                999060 non-null  int32
 1   user_id                 999060 non-null  int32
 2   eval_set                999060 non-null  object
 3   order_number            999060 non-null  int32
 4   order_dow               999060 non-null  int8
 5   order_hour_of_day       999060 non-null  float32
 6   days_since_prior_order  935521 non-null  float64
 7   product_id              999060 non-null  int32
 8   add_to_cart_order       999060 non-null  int32
 9   reordered               999060 non-null  int32
 10  product_name            999060 non-null  object
 11  aisle_id                999060 non-null  int32
 12  department_id           999060 non-null  int32
 13  prices                  999060 non-null  float32
 14  _merge                  999060 non-null  category
 15  price_range             999060 non-null  object
 16  Busiest days            999060 non-null  object
 17  busiest_period_of_day   999060 non-null  object
 18  max_order               999060 non-null  int32
 19  loyalty_flag            999060 non-null  object
dtypes: category(1), float32(2), float64(1), int32(9), int8(1), object(6)
memory usage: 104.8+ MB

In [22]:
ords_prods_merge['max_order']=ords_prods_merge['max_order'].astype('int8')

In [23]:
###task 8

In [25]:
##Q5: The marketing team at Instacart wants to know whether there’s a difference between the spending habits of the three types of customers you identified.
ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max', 'sum']})

                     prices
                       mean  min      max        sum
loyalty_flag
Loyal customer     9.082290  1.0  99999.0  2923416.5
New customer      15.854605  1.0  99999.0  3096816.5
Regular customer  11.142378  1.0  99999.0  5368988.5

In [26]:
##it shows that loyal customers are purchasing cheaper products than new and regualr, also it shows that new customer average prices are more than others spend

In [31]:
##The team now wants to target different types of spenders in their marketing campaigns
ords_prods_merge['avg_price'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [32]:
##Create a spending flag for each user based on the average price across all their orders using the following criteri

In [33]:
ords_prods_merge.loc[ords_prods_merge['avg_price'] > 10, 'spending_flag'] = 'High spender'
ords_prods_merge.loc[ords_prods_merge['avg_price'] < 10, 'spending_flag'] = 'Low spender'

In [34]:
ords_prods_merge['spending_flag'].value_counts(dropna = False)

Low spender     977674
High spender     21386
Name: spending_flag, dtype: int64

In [38]:
##the Instacart team wants you to determine frequent versus non-frequent customers.
ords_prods_merge['mdian_freq'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [40]:
##
ords_prods_merge.loc[ords_prods_merge['mdian_freq'] > 20, 'Cust_frequency'] = 'Non-frequent customer'
ords_prods_merge.loc[ords_prods_merge['mdian_freq'] > 10 & (ords_prods_merge['mdian_freq'] <= 20), 'Cust_frequency'] = 'Non-frequent customer'
ords_prods_merge.loc[ords_prods_merge['mdian_freq'] <= 10, 'Cust_frequency'] = 'Frequent customer'

In [41]:
ords_prods_merge.head(15)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,_merge,price_range,Busiest days,busiest_period_of_day,max_order,loyalty_flag,avg_price,spending_flag,mdian_freq,Cust_frequency
0,2539329,1,prior,1,2,8.0,NaN,196,1,0,...,both,Mid-range product,Regularly days,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
1,2398795,1,prior,2,3,7.0,15.0,196,1,1,...,both,Mid-range product,Slowest days,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
2,473747,1,prior,3,3,12.0,21.0,196,1,1,...,both,Mid-range product,Slowest days,Most orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
3,2254736,1,prior,4,4,7.0,29.0,196,1,1,...,both,Mid-range product,Slowest days,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
4,431534,1,prior,5,4,15.0,28.0,196,1,1,...,both,Mid-range product,Slowest days,Most orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
5,3367565,1,prior,6,2,7.0,19.0,196,1,1,...,both,Mid-range product,Regularly days,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
6,550135,1,prior,7,1,9.0,20.0,196,1,1,...,both,Mid-range product,Busiest days,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
7,3108588,1,prior,8,1,14.0,14.0,196,2,1,...,both,Mid-range product,Busiest days,Most orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
8,2295261,1,prior,9,1,16.0,0.0,196,4,1,...,both,Mid-range product,Busiest days,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
9,2550362,1,prior,10,4,8.0,30.0,196,1,1,...,both,Mid-range product,Slowest days,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
10,2968173,15,prior,15,1,9.0,7.0,196,2,0,...,both,Mid-range product,Busiest days,Average orders,22,Regular customer,3.980556,Low spender,10.0,Frequent customer
11,1870022,15,prior,17,2,16.0,8.0,196,6,1,...,both,Mid-range product,Regularly days,Average orders,22,Regular customer,3.980556,Low spender,10.0,Frequent customer
12,1911383,15,prior,18,2,11.0,7.0,196,1,1,...,both,Mid-range product,Regularly days,Most orders,22,Regular customer,3.980556,Low spender,10.0,Frequent customer
13,2715276,15,prior,21,1,9.0,7.0,196,1,1,...,both,Mid-range product,Busiest days,Average orders,22,Regular customer,3.980556,Low spender,10.0,Frequent customer
14,487368,15,prior,22,1,10.0,14.0,196,1,1,...,both,Mid-range product,Busiest days,Most orders,22,Regular customer,3.980556,Low spender,10.0,Frequent customer

In [42]:
#Checking the count of 'order_freq_flag' values
ords_prods_merge['Cust_frequency'].value_counts(dropna = False)

Frequent customer        664304
Non-frequent customer    334756
Name: Cust_frequency, dtype: int64

In [43]:
ords_prods_merge.to_pickle(os.path.join(path,'Data','Prepared Data','orders_products_merged_aggregated.pkl'))